### ISSUE TITLE
Contributions welcome!

### ISSUE THREAD

**Issue by imanhodjaev** [imanhodjaev/every#3]
[Hacktoberfest 2018](https://hacktoberfest.digitalocean.com/) is happening now and I'd like to open this repository to all contributions!

![68747470733a2f2f6861636b746f626572666573742e6469676974616c6f6365616e2e636f6d2f6173736574732f6861636b746f626572666573742d323031382d736f6369616c2d636172642d63386432653134383966363437663265306132366536663539386164656237363038373238313839303562](https://user-images.githubusercontent.com/354868/46934343-b27bf380-d057-11e8-9544-0f425ec3d6c0.png)

Try to open an issue before doing too much work, for discussion.

**Comment by janpieper** [comment]
#7 :wink:

**Comment by imanhodjaev** [comment]
Thanks all for participation! 🎃
