### ISSUE TITLE
Return value should be milliseconds

### ISSUE THREAD

**Issue by bobwaycott** [imanhodjaev/every#6]
If `Every` is intended to be used with `Process.send_after/3`, shouldn’t results always be in milliseconds? The examples show a lot of repetition in converting every result to milliseconds, and it’d be much friendlier and less verbose if `Every` returned results that could be used without further manipulation.

**Comment by imanhodjaev** [comment]
@bobwaycott yes it makes sense and thanks for pointing this out.

**Comment by imanhodjaev** [comment]
These adjustments are in master now, so will be released soon.
